# Generated by Django 5.2.4 on 2025-07-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_profile_birth_date_phoneonlylogincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
