# Generated by Django 5.2.4 on 2025-07-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activated_code',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
