# Generated by Django 5.2.4 on 2025-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_activated_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activated_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
