# Generated by Django 5.2.4 on 2025-07-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profile_activated_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activated_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='activated_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile'),
        ),
    ]
