# Generated by Django 5.2.4 on 2025-07-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_profile_activated_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activated_invite',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile'),
        ),
    ]
